packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  workerd: true
catalog:
  drizzle-orm: ^0.45.2
  typescript: ^6.0.2
  vitest: ^4.1.2
  wrangler: ^4.78.0
  zod: ^4.3.6
