packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  workerd: true
catalog:
  '@cloudflare/vitest-pool-workers': ^0.14.2
  '@vitest/coverage-v8': ^4.1.4
  drizzle-orm: ^0.45.2
  typescript: ^6.0.2
  vitest: ^4.1.4
  wrangler: ^4.81.0
  zod: ^4.3.6
