name = "versioneer-api"
main = "src/index.ts"
compatibility_date = "2025-01-13"

[vars]
ENVIRONMENT = "dev"
CF_ACCESS_TEAM_DOMAIN = ""
CF_ACCESS_AUD = ""
ADMIN_ORIGIN = "http://localhost:5173"

[[d1_databases]]
binding = "DB"
database_name = "versioneer-db-dev"
database_id = "0af7b90f-a8b3-4392-8dd9-73b12e3e48ff"

[[r2_buckets]]
binding = "RAW_BUCKET"
bucket_name = "versioneer-raw-dev"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "59fffb96b80a45d586051951e8043f3f"

[[kv_namespaces]]
binding = "CONFIG_KV"
id = "6d27b272dbd9466fb1d7bcc2ce83f501"

[[queues.producers]]
binding = "SOURCE_FETCH_QUEUE"
queue = "versioneer-source-fetch-dev"

[[queues.producers]]
binding = "SOURCE_PARSE_QUEUE"
queue = "versioneer-source-parse-dev"

[[queues.producers]]
binding = "ARTIFACT_VERIFY_QUEUE"
queue = "versioneer-artifact-verify-dev"

[[queues.producers]]
binding = "RECOMPUTE_LATEST_QUEUE"
queue = "versioneer-recompute-latest-dev"

[env.staging]
[env.staging.vars]
ENVIRONMENT = "staging"
CF_ACCESS_TEAM_DOMAIN = "yourteam.cloudflareaccess.com"
CF_ACCESS_AUD = ""
ADMIN_ORIGIN = ""

[env.production]
[env.production.vars]
ENVIRONMENT = "production"
CF_ACCESS_TEAM_DOMAIN = "yourteam.cloudflareaccess.com"
CF_ACCESS_AUD = ""
ADMIN_ORIGIN = ""
