/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourcesIndexRouteImport } from './routes/sources/index'
import { Route as ReviewQueueIndexRouteImport } from './routes/review-queue/index'
import { Route as ReleasesIndexRouteImport } from './routes/releases/index'
import { Route as OverridesIndexRouteImport } from './routes/overrides/index'
import { Route as JobFailuresIndexRouteImport } from './routes/job-failures/index'
import { Route as FeedbackIndexRouteImport } from './routes/feedback/index'
import { Route as ExecutionsIndexRouteImport } from './routes/executions/index'
import { Route as DiscoveredAppsIndexRouteImport } from './routes/discovered-apps/index'
import { Route as AuditLogIndexRouteImport } from './routes/audit-log/index'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as SourcesSourceIdRouteImport } from './routes/sources/$sourceId'
import { Route as ReleasesReleaseIdRouteImport } from './routes/releases/$releaseId'
import { Route as AppsAppIdRouteImport } from './routes/apps/$appId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewQueueIndexRoute = ReviewQueueIndexRouteImport.update({
  id: '/review-queue/',
  path: '/review-queue/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesIndexRoute = ReleasesIndexRouteImport.update({
  id: '/releases/',
  path: '/releases/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverridesIndexRoute = OverridesIndexRouteImport.update({
  id: '/overrides/',
  path: '/overrides/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobFailuresIndexRoute = JobFailuresIndexRouteImport.update({
  id: '/job-failures/',
  path: '/job-failures/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackIndexRoute = FeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionsIndexRoute = ExecutionsIndexRouteImport.update({
  id: '/executions/',
  path: '/executions/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveredAppsIndexRoute = DiscoveredAppsIndexRouteImport.update({
  id: '/discovered-apps/',
  path: '/discovered-apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogIndexRoute = AuditLogIndexRouteImport.update({
  id: '/audit-log/',
  path: '/audit-log/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesSourceIdRoute = SourcesSourceIdRouteImport.update({
  id: '/sources/$sourceId',
  path: '/sources/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesReleaseIdRoute = ReleasesReleaseIdRouteImport.update({
  id: '/releases/$releaseId',
  path: '/releases/$releaseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAppIdRoute = AppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/releases/$releaseId': typeof ReleasesReleaseIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/apps/': typeof AppsIndexRoute
  '/audit-log/': typeof AuditLogIndexRoute
  '/discovered-apps/': typeof DiscoveredAppsIndexRoute
  '/executions/': typeof ExecutionsIndexRoute
  '/feedback/': typeof FeedbackIndexRoute
  '/job-failures/': typeof JobFailuresIndexRoute
  '/overrides/': typeof OverridesIndexRoute
  '/releases/': typeof ReleasesIndexRoute
  '/review-queue/': typeof ReviewQueueIndexRoute
  '/sources/': typeof SourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/releases/$releaseId': typeof ReleasesReleaseIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/apps': typeof AppsIndexRoute
  '/audit-log': typeof AuditLogIndexRoute
  '/discovered-apps': typeof DiscoveredAppsIndexRoute
  '/executions': typeof ExecutionsIndexRoute
  '/feedback': typeof FeedbackIndexRoute
  '/job-failures': typeof JobFailuresIndexRoute
  '/overrides': typeof OverridesIndexRoute
  '/releases': typeof ReleasesIndexRoute
  '/review-queue': typeof ReviewQueueIndexRoute
  '/sources': typeof SourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/releases/$releaseId': typeof ReleasesReleaseIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/apps/': typeof AppsIndexRoute
  '/audit-log/': typeof AuditLogIndexRoute
  '/discovered-apps/': typeof DiscoveredAppsIndexRoute
  '/executions/': typeof ExecutionsIndexRoute
  '/feedback/': typeof FeedbackIndexRoute
  '/job-failures/': typeof JobFailuresIndexRoute
  '/overrides/': typeof OverridesIndexRoute
  '/releases/': typeof ReleasesIndexRoute
  '/review-queue/': typeof ReviewQueueIndexRoute
  '/sources/': typeof SourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps/$appId'
    | '/releases/$releaseId'
    | '/sources/$sourceId'
    | '/apps/'
    | '/audit-log/'
    | '/discovered-apps/'
    | '/executions/'
    | '/feedback/'
    | '/job-failures/'
    | '/overrides/'
    | '/releases/'
    | '/review-queue/'
    | '/sources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps/$appId'
    | '/releases/$releaseId'
    | '/sources/$sourceId'
    | '/apps'
    | '/audit-log'
    | '/discovered-apps'
    | '/executions'
    | '/feedback'
    | '/job-failures'
    | '/overrides'
    | '/releases'
    | '/review-queue'
    | '/sources'
  id:
    | '__root__'
    | '/'
    | '/apps/$appId'
    | '/releases/$releaseId'
    | '/sources/$sourceId'
    | '/apps/'
    | '/audit-log/'
    | '/discovered-apps/'
    | '/executions/'
    | '/feedback/'
    | '/job-failures/'
    | '/overrides/'
    | '/releases/'
    | '/review-queue/'
    | '/sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsAppIdRoute: typeof AppsAppIdRoute
  ReleasesReleaseIdRoute: typeof ReleasesReleaseIdRoute
  SourcesSourceIdRoute: typeof SourcesSourceIdRoute
  AppsIndexRoute: typeof AppsIndexRoute
  AuditLogIndexRoute: typeof AuditLogIndexRoute
  DiscoveredAppsIndexRoute: typeof DiscoveredAppsIndexRoute
  ExecutionsIndexRoute: typeof ExecutionsIndexRoute
  FeedbackIndexRoute: typeof FeedbackIndexRoute
  JobFailuresIndexRoute: typeof JobFailuresIndexRoute
  OverridesIndexRoute: typeof OverridesIndexRoute
  ReleasesIndexRoute: typeof ReleasesIndexRoute
  ReviewQueueIndexRoute: typeof ReviewQueueIndexRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/': {
      id: '/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-queue/': {
      id: '/review-queue/'
      path: '/review-queue'
      fullPath: '/review-queue/'
      preLoaderRoute: typeof ReviewQueueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases/': {
      id: '/releases/'
      path: '/releases'
      fullPath: '/releases/'
      preLoaderRoute: typeof ReleasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overrides/': {
      id: '/overrides/'
      path: '/overrides'
      fullPath: '/overrides/'
      preLoaderRoute: typeof OverridesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-failures/': {
      id: '/job-failures/'
      path: '/job-failures'
      fullPath: '/job-failures/'
      preLoaderRoute: typeof JobFailuresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/': {
      id: '/feedback/'
      path: '/feedback'
      fullPath: '/feedback/'
      preLoaderRoute: typeof FeedbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executions/': {
      id: '/executions/'
      path: '/executions'
      fullPath: '/executions/'
      preLoaderRoute: typeof ExecutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovered-apps/': {
      id: '/discovered-apps/'
      path: '/discovered-apps'
      fullPath: '/discovered-apps/'
      preLoaderRoute: typeof DiscoveredAppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log/': {
      id: '/audit-log/'
      path: '/audit-log'
      fullPath: '/audit-log/'
      preLoaderRoute: typeof AuditLogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$sourceId': {
      id: '/sources/$sourceId'
      path: '/sources/$sourceId'
      fullPath: '/sources/$sourceId'
      preLoaderRoute: typeof SourcesSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases/$releaseId': {
      id: '/releases/$releaseId'
      path: '/releases/$releaseId'
      fullPath: '/releases/$releaseId'
      preLoaderRoute: typeof ReleasesReleaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$appId': {
      id: '/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AppsAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsAppIdRoute: AppsAppIdRoute,
  ReleasesReleaseIdRoute: ReleasesReleaseIdRoute,
  SourcesSourceIdRoute: SourcesSourceIdRoute,
  AppsIndexRoute: AppsIndexRoute,
  AuditLogIndexRoute: AuditLogIndexRoute,
  DiscoveredAppsIndexRoute: DiscoveredAppsIndexRoute,
  ExecutionsIndexRoute: ExecutionsIndexRoute,
  FeedbackIndexRoute: FeedbackIndexRoute,
  JobFailuresIndexRoute: JobFailuresIndexRoute,
  OverridesIndexRoute: OverridesIndexRoute,
  ReleasesIndexRoute: ReleasesIndexRoute,
  ReviewQueueIndexRoute: ReviewQueueIndexRoute,
  SourcesIndexRoute: SourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
