/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourcesIndexRouteImport } from './routes/sources/index'
import { Route as ReviewIndexRouteImport } from './routes/review/index'
import { Route as ReleasesIndexRouteImport } from './routes/releases/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as FeedbackIndexRouteImport } from './routes/feedback/index'
import { Route as DiscoveredAppsIndexRouteImport } from './routes/discovered-apps/index'
import { Route as AuditLogIndexRouteImport } from './routes/audit-log/index'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as SourcesSourceIdRouteImport } from './routes/sources/$sourceId'
import { Route as ReleasesReleaseIdRouteImport } from './routes/releases/$releaseId'
import { Route as JobsRunsRouteImport } from './routes/jobs/runs'
import { Route as JobsFailuresRouteImport } from './routes/jobs/failures'
import { Route as AppsAppIdRouteImport } from './routes/apps/$appId'
import { Route as AppsAppIdIndexRouteImport } from './routes/apps/$appId.index'
import { Route as AppsAppIdSourcesRouteImport } from './routes/apps/$appId.sources'
import { Route as AppsAppIdReleasesRouteImport } from './routes/apps/$appId.releases'
import { Route as AppsAppIdAliasesRouteImport } from './routes/apps/$appId.aliases'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAssetsSplatRouteImport } from './routes/api/assets/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesIndexRoute = SourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesIndexRoute = ReleasesIndexRouteImport.update({
  id: '/releases/',
  path: '/releases/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackIndexRoute = FeedbackIndexRouteImport.update({
  id: '/feedback/',
  path: '/feedback/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveredAppsIndexRoute = DiscoveredAppsIndexRouteImport.update({
  id: '/discovered-apps/',
  path: '/discovered-apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogIndexRoute = AuditLogIndexRouteImport.update({
  id: '/audit-log/',
  path: '/audit-log/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesSourceIdRoute = SourcesSourceIdRouteImport.update({
  id: '/sources/$sourceId',
  path: '/sources/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesReleaseIdRoute = ReleasesReleaseIdRouteImport.update({
  id: '/releases/$releaseId',
  path: '/releases/$releaseId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRunsRoute = JobsRunsRouteImport.update({
  id: '/jobs/runs',
  path: '/jobs/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsFailuresRoute = JobsFailuresRouteImport.update({
  id: '/jobs/failures',
  path: '/jobs/failures',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAppIdRoute = AppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAppIdIndexRoute = AppsAppIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppsAppIdRoute,
} as any)
const AppsAppIdSourcesRoute = AppsAppIdSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppsAppIdRoute,
} as any)
const AppsAppIdReleasesRoute = AppsAppIdReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => AppsAppIdRoute,
} as any)
const AppsAppIdAliasesRoute = AppsAppIdAliasesRouteImport.update({
  id: '/aliases',
  path: '/aliases',
  getParentRoute: () => AppsAppIdRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsSplatRoute = ApiAssetsSplatRouteImport.update({
  id: '/api/assets/$',
  path: '/api/assets/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/apps/$appId': typeof AppsAppIdRouteWithChildren
  '/jobs/failures': typeof JobsFailuresRoute
  '/jobs/runs': typeof JobsRunsRoute
  '/releases/$releaseId': typeof ReleasesReleaseIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/apps/': typeof AppsIndexRoute
  '/audit-log/': typeof AuditLogIndexRoute
  '/discovered-apps/': typeof DiscoveredAppsIndexRoute
  '/feedback/': typeof FeedbackIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/releases/': typeof ReleasesIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/api/assets/$': typeof ApiAssetsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/apps/$appId/aliases': typeof AppsAppIdAliasesRoute
  '/apps/$appId/releases': typeof AppsAppIdReleasesRoute
  '/apps/$appId/sources': typeof AppsAppIdSourcesRoute
  '/apps/$appId/': typeof AppsAppIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/jobs/failures': typeof JobsFailuresRoute
  '/jobs/runs': typeof JobsRunsRoute
  '/releases/$releaseId': typeof ReleasesReleaseIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/apps': typeof AppsIndexRoute
  '/audit-log': typeof AuditLogIndexRoute
  '/discovered-apps': typeof DiscoveredAppsIndexRoute
  '/feedback': typeof FeedbackIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/releases': typeof ReleasesIndexRoute
  '/review': typeof ReviewIndexRoute
  '/sources': typeof SourcesIndexRoute
  '/api/assets/$': typeof ApiAssetsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/apps/$appId/aliases': typeof AppsAppIdAliasesRoute
  '/apps/$appId/releases': typeof AppsAppIdReleasesRoute
  '/apps/$appId/sources': typeof AppsAppIdSourcesRoute
  '/apps/$appId': typeof AppsAppIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/apps/$appId': typeof AppsAppIdRouteWithChildren
  '/jobs/failures': typeof JobsFailuresRoute
  '/jobs/runs': typeof JobsRunsRoute
  '/releases/$releaseId': typeof ReleasesReleaseIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
  '/apps/': typeof AppsIndexRoute
  '/audit-log/': typeof AuditLogIndexRoute
  '/discovered-apps/': typeof DiscoveredAppsIndexRoute
  '/feedback/': typeof FeedbackIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/releases/': typeof ReleasesIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/sources/': typeof SourcesIndexRoute
  '/api/assets/$': typeof ApiAssetsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/apps/$appId/aliases': typeof AppsAppIdAliasesRoute
  '/apps/$appId/releases': typeof AppsAppIdReleasesRoute
  '/apps/$appId/sources': typeof AppsAppIdSourcesRoute
  '/apps/$appId/': typeof AppsAppIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/apps/$appId'
    | '/jobs/failures'
    | '/jobs/runs'
    | '/releases/$releaseId'
    | '/sources/$sourceId'
    | '/apps/'
    | '/audit-log/'
    | '/discovered-apps/'
    | '/feedback/'
    | '/jobs/'
    | '/releases/'
    | '/review/'
    | '/sources/'
    | '/api/assets/$'
    | '/api/auth/$'
    | '/apps/$appId/aliases'
    | '/apps/$appId/releases'
    | '/apps/$appId/sources'
    | '/apps/$appId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/jobs/failures'
    | '/jobs/runs'
    | '/releases/$releaseId'
    | '/sources/$sourceId'
    | '/apps'
    | '/audit-log'
    | '/discovered-apps'
    | '/feedback'
    | '/jobs'
    | '/releases'
    | '/review'
    | '/sources'
    | '/api/assets/$'
    | '/api/auth/$'
    | '/apps/$appId/aliases'
    | '/apps/$appId/releases'
    | '/apps/$appId/sources'
    | '/apps/$appId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/apps/$appId'
    | '/jobs/failures'
    | '/jobs/runs'
    | '/releases/$releaseId'
    | '/sources/$sourceId'
    | '/apps/'
    | '/audit-log/'
    | '/discovered-apps/'
    | '/feedback/'
    | '/jobs/'
    | '/releases/'
    | '/review/'
    | '/sources/'
    | '/api/assets/$'
    | '/api/auth/$'
    | '/apps/$appId/aliases'
    | '/apps/$appId/releases'
    | '/apps/$appId/sources'
    | '/apps/$appId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AppsAppIdRoute: typeof AppsAppIdRouteWithChildren
  JobsFailuresRoute: typeof JobsFailuresRoute
  JobsRunsRoute: typeof JobsRunsRoute
  ReleasesReleaseIdRoute: typeof ReleasesReleaseIdRoute
  SourcesSourceIdRoute: typeof SourcesSourceIdRoute
  AppsIndexRoute: typeof AppsIndexRoute
  AuditLogIndexRoute: typeof AuditLogIndexRoute
  DiscoveredAppsIndexRoute: typeof DiscoveredAppsIndexRoute
  FeedbackIndexRoute: typeof FeedbackIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  ReleasesIndexRoute: typeof ReleasesIndexRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
  SourcesIndexRoute: typeof SourcesIndexRoute
  ApiAssetsSplatRoute: typeof ApiAssetsSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/': {
      id: '/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof SourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases/': {
      id: '/releases/'
      path: '/releases'
      fullPath: '/releases/'
      preLoaderRoute: typeof ReleasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/': {
      id: '/feedback/'
      path: '/feedback'
      fullPath: '/feedback/'
      preLoaderRoute: typeof FeedbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovered-apps/': {
      id: '/discovered-apps/'
      path: '/discovered-apps'
      fullPath: '/discovered-apps/'
      preLoaderRoute: typeof DiscoveredAppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log/': {
      id: '/audit-log/'
      path: '/audit-log'
      fullPath: '/audit-log/'
      preLoaderRoute: typeof AuditLogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$sourceId': {
      id: '/sources/$sourceId'
      path: '/sources/$sourceId'
      fullPath: '/sources/$sourceId'
      preLoaderRoute: typeof SourcesSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases/$releaseId': {
      id: '/releases/$releaseId'
      path: '/releases/$releaseId'
      fullPath: '/releases/$releaseId'
      preLoaderRoute: typeof ReleasesReleaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/runs': {
      id: '/jobs/runs'
      path: '/jobs/runs'
      fullPath: '/jobs/runs'
      preLoaderRoute: typeof JobsRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/failures': {
      id: '/jobs/failures'
      path: '/jobs/failures'
      fullPath: '/jobs/failures'
      preLoaderRoute: typeof JobsFailuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$appId': {
      id: '/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AppsAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$appId/': {
      id: '/apps/$appId/'
      path: '/'
      fullPath: '/apps/$appId/'
      preLoaderRoute: typeof AppsAppIdIndexRouteImport
      parentRoute: typeof AppsAppIdRoute
    }
    '/apps/$appId/sources': {
      id: '/apps/$appId/sources'
      path: '/sources'
      fullPath: '/apps/$appId/sources'
      preLoaderRoute: typeof AppsAppIdSourcesRouteImport
      parentRoute: typeof AppsAppIdRoute
    }
    '/apps/$appId/releases': {
      id: '/apps/$appId/releases'
      path: '/releases'
      fullPath: '/apps/$appId/releases'
      preLoaderRoute: typeof AppsAppIdReleasesRouteImport
      parentRoute: typeof AppsAppIdRoute
    }
    '/apps/$appId/aliases': {
      id: '/apps/$appId/aliases'
      path: '/aliases'
      fullPath: '/apps/$appId/aliases'
      preLoaderRoute: typeof AppsAppIdAliasesRouteImport
      parentRoute: typeof AppsAppIdRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/$': {
      id: '/api/assets/$'
      path: '/api/assets/$'
      fullPath: '/api/assets/$'
      preLoaderRoute: typeof ApiAssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppsAppIdRouteChildren {
  AppsAppIdAliasesRoute: typeof AppsAppIdAliasesRoute
  AppsAppIdReleasesRoute: typeof AppsAppIdReleasesRoute
  AppsAppIdSourcesRoute: typeof AppsAppIdSourcesRoute
  AppsAppIdIndexRoute: typeof AppsAppIdIndexRoute
}

const AppsAppIdRouteChildren: AppsAppIdRouteChildren = {
  AppsAppIdAliasesRoute: AppsAppIdAliasesRoute,
  AppsAppIdReleasesRoute: AppsAppIdReleasesRoute,
  AppsAppIdSourcesRoute: AppsAppIdSourcesRoute,
  AppsAppIdIndexRoute: AppsAppIdIndexRoute,
}

const AppsAppIdRouteWithChildren = AppsAppIdRoute._addFileChildren(
  AppsAppIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AppsAppIdRoute: AppsAppIdRouteWithChildren,
  JobsFailuresRoute: JobsFailuresRoute,
  JobsRunsRoute: JobsRunsRoute,
  ReleasesReleaseIdRoute: ReleasesReleaseIdRoute,
  SourcesSourceIdRoute: SourcesSourceIdRoute,
  AppsIndexRoute: AppsIndexRoute,
  AuditLogIndexRoute: AuditLogIndexRoute,
  DiscoveredAppsIndexRoute: DiscoveredAppsIndexRoute,
  FeedbackIndexRoute: FeedbackIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  ReleasesIndexRoute: ReleasesIndexRoute,
  ReviewIndexRoute: ReviewIndexRoute,
  SourcesIndexRoute: SourcesIndexRoute,
  ApiAssetsSplatRoute: ApiAssetsSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
